### PR TITLE
fix analyzer 6.0 errors

### PR DESCRIPTION
**Pull request by The-Redhat**
based on changes did here https://github.com/dart-lang/sdk/blob/fae9e418ea380f46b5b067d020403d505aa78eff/pkg/analyzer/lib/src/error/imports_verifier.dart

### CODE REVIEW

**Review by ghozay19 — APPROVED** [review]

**Comment by ghozay19** [comment]
lgtm. 
already tested on my own code.

**Comment by saltorre** [comment]
Can someone approve and merge, please?

**Comment by bvoq** [comment]
Yep, please merge these changes!

**Comment by bvoq** [comment]
Yep, please merge these changes! @santitigaga @juancgalvis
Main doesn't work at the moment.
Thanks @The-Redhat

**Comment by santitigaga** [comment]
thanks for the contribution, I'm reviewing it

**Review by santitigaga — APPROVED** [review]

**Comment by ghozay19** [comment]
thanks

**Comment by bvoq** [comment]
thanks!

**Comment by bvoq** [comment]
Can you upload this to https://pub.dev ?
Unfortunately, the version on pub.dev doesn't run at the moment. Thanks!

**Comment by bvoq** [comment]
Thanks for updating pub.dev!

**Pull request merged**
