### PR TITLE
Add prefer single quotes rule

### PR DESCRIPTION
**Pull request by byshy**
This PR has changes from [this PR](https://github.com/bancolombia/dart-code-linter/pull/150), please make sure to review that first

What's new?
- Adding a new rule that prefers the use of single quotes instead of double quotes when creating a string

### CODE REVIEW

**Review by santitigaga — DISMISSED** [review]

**Comment by santitigaga** [comment]
please solve https://github.com/bancolombia/dart-code-linter/pull/150, In order to complete this .

Thanks for your help @byshy

**Comment by santitigaga** [comment]
@byshy please pull the changes from trunk to merge this PR

**Comment by byshy** [comment]
All changes from trunk are merged and the branch is ready for review

**Review by santitigaga — APPROVED** [review]
Good Job!!!

**Pull request merged**
