### PR TITLE
update http and uuid dependency

### PR DESCRIPTION
**Pull request by The-Redhat**

### CODE REVIEW

**Comment by santitigaga** [comment]
Thank you for the update @The-Redhat

**Comment by The-Redhat** [comment]
Hey @santitigaga I updated the github actions pipeline flutter version. It should work now

**Review by santitigaga — APPROVED** [review]

**Comment by santitigaga** [comment]
Great Job @The-Redhat

**Comment by The-Redhat** [comment]
@santitigaga are you planning to release a new version to pub.dev soon?

**Pull request merged**
