### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by alperenekin**
In the newer Flutter versions(3.19 in my case), it is not possible to build the app due to [File](https://pub.dev/packages/file/changelog) dependency.

### CODE REVIEW

**Comment by bvoq** [comment]
If need be this can also be `file: >=6.0.0 <8.0.0`. But please support the newest flutter versions!

**Comment by bvoq** [comment]
@santitigaga please merge it 😇

**Comment by danielgomezrico** [comment]
This fixes:
- https://github.com/bancolombia/dart-code-linter/issues/128

**Comment by danielgomezrico** [comment]
@alperenekin Im curious, why updating `pub_updater` is important?

**Comment by alperenekin** [comment]
@danielgomezrico 
```
Because pub_updater <0.4.0 depends on process ^4.2.3 which depends on file ^6.0.0, pub_updater <0.4.0 requires file ^6.0.0.
So, because dart_code_linter depends on both file ^7.0.0 and pub_updater ^0.3.0, version solving failed
```

I updated the PR as it is suggested by @bvoq. Using a range seems to work fine, since it is actually comptabile with the older version.

**Comment by santitigaga** [comment]
@alperenekin Thanks for the help!!!

**Review by santitigaga — APPROVED** [review]

**Pull request merged**
